## Sklearn
* out of the box ml modeling toolkit
* funcitonality for:
    * wrangling data
    * model
    * evaluation
* integreates with pandas and numpy

In [109]:
import copy


In [156]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

iris = load_iris()
data = iris["data"]
labels = iris["target_names"]
feature_columns = iris["feature_names"]

df = pd.DataFrame(data, columns = feature_columns)
df["label"] = np.array([labels[x] for x in iris["target"]])

In [157]:
df.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   

    label  
0  setosa

In [158]:
x = df.drop("label", 1)
y = df["label"]



### Clustering
* https://scikit-learn.org/stable/modules/clustering.html
* https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_score.html

In [121]:
from sklearn.cluster import KMeans

In [122]:
kmeans = KMeans(3).fit(x)

In [123]:
result = kmeans.labels_
print(result)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: label, Length: 150, dtype: object


In [124]:
kmeans.cluster_centers_

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [125]:
from sklearn.metrics import silhouette_score, f1_score, precision_score, accuracy_score

In [126]:
score = silhouette_score(y,kmeans.labels_)

ValueError: could not convert string to float: 'setosa'

In [54]:
score

0.5528190123564102

In [55]:
ks = [2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    kmeans = KMeans(k).fit(x)
    scores.append(silhouette_score(x,kmeans.labels_))

In [56]:
for i in zip(ks, scores):
    print(i)

(2, 0.6810461692117465)
(3, 0.5528190123564102)
(4, 0.49805050499728803)
(5, 0.48874888709310654)
(6, 0.36598336415829236)
(7, 0.34521786463700094)
(8, 0.350060295968675)
(9, 0.32233069884845983)
(10, 0.30973766533913044)


In [57]:
kmeans = KMeans(3).fit(x)

In [58]:
assign_dct = dict(x for x in zip(x.index, kmeans.labels_))

In [59]:
assign_df = pd.DataFrame({
    "observation": x.index,
    "label": kmeans.labels_
})

In [60]:
assign_df.head(5)

observation  label
0            0      0
1            1      0
2            2      0
3            3      0
4            4      0

* https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html#sklearn.cluster.AgglomerativeClustering

In [61]:
from sklearn.cluster import AgglomerativeClustering

In [62]:
agglom = AgglomerativeClustering(n_clusters = 3).fit(x)

In [63]:
agglom.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int64)

In [127]:
assign_df["agglom_labels"] = agglom.labels_

In [128]:
assign_df["diff"] = [True if i[0] == i[1] else False for i in 
                     zip(assign_df["label"].tolist(), assign_df["agglom_labels"].tolist())]

In [129]:
assign_df["diff1"] = np.where(assign_df["label"] == assign_df["agglom_labels"], True, False)

In [130]:
assign_df

observation  label  agglom_labels   diff  diff1
0              0      0              1  False  False
1              1      0              1  False  False
2              2      0              1  False  False
3              3      0              1  False  False
4              4      0              1  False  False
..           ...    ...            ...    ...    ...
145          145      2              2   True   True
146          146      1              0  False  False
147          147      2              2   True   True
148          148      2              2   True   True
149          149      1              0  False  False

[150 rows x 5 columns]

In [131]:
from sklearn.feature_extraction.text import CountVectorizer

In [132]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [133]:
vectorizer = CountVectorizer()

In [134]:
x = vectorizer.fit_transform(corpus)

In [135]:
df = pd.DataFrame(x.toarray(), columns = vectorizer.get_feature_names())

In [136]:
df

and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         2      0   1    0       1    1      0     1
2    1         0      0   1    1       0    1      1     1
3    0         1      1   1    0       0    1      0     1

In [137]:
kmeans = KMeans(2).fit(df)

In [138]:
for i in zip(corpus, kmeans.labels_):
    print(i)

('This is the first document.', 1)
('This document is the second document.', 1)
('And this is the third one.', 0)
('Is this the first document?', 1)


* consider grouping articles
* corpus is a bunch of documents of articles
* we could cluster them based on the words in them
* and classify new articles as they come in

* https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html#sklearn.cluster.DBSCAN
* density based clustering
* dbscan labels noise (items that don't fit into clusters well) as -1.

In [139]:
from sklearn.cluster import DBSCAN

In [142]:

iris = load_iris()
data = iris["data"]
labels = iris["target_names"]
feature_columns = iris["feature_names"]

df = pd.DataFrame(data, columns = feature_columns)

scan = DBSCAN().fit(df)

In [144]:
scan.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
      dtype=int64)

* in this case, with iris, we have actual labels, ground truth
* say had a sample of data with labels
* we could cluster the items we have labels for and feed that into a classificaiton model
* if that classification model performs well, we could feel more comfortable applying that to unlabeled data

In [145]:
from sklearn.tree import DecisionTreeClassifier

In [146]:
kmeans = KMeans(3).fit(x)

In [147]:
labels = kmeans.labels_

ValueError: Number of labels=150 does not match number of samples=4

In [149]:
yhat = dt.predict(x)

NameError: name 'dt' is not defined

In [85]:
# if our decision tree is good we could save it here and apply it to new, unlabeled data
# many times you will run into cases where you have portions of data that's been labeled
# but you'd like to label the entire sample

In [83]:
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

    label  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [88]:
x_sample = copy.copy(x)
x_sample["label"] = "?"

In [89]:
concat_df = pd.concat([df, x_sample])

In [90]:
concat_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

    label  
0  setosa  
1  setosa  
2  setosa

In [91]:
concat_df.tail(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

    label  
147     ?  
148     ?  
149     ?

### Classification

* https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier

In [151]:
dt = DecisionTreeClassifier()

In [152]:
dt

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [95]:
yhat = dt.predict(x)

In [98]:
# predict wants a list of lists
# or a 2d numpy array
# so you have to wrap single observations
#dt.predict([1,2,3,4])

In [97]:
dt.predict([[1,2,3,4]])

array(['virginica'], dtype=object)

* https://scikit-learn.org/stable/modules/model_persistence.html
* in the specific case of scikit-learn, it may be better to use joblib’s replacement of pickle (dump & load), which is more efficient on objects that carry large numpy arrays internally as is often the case for fitted scikit-learn estimators
* pickle is standard library in C while joblib is pure python, so it we aren't saving items with large numpy arrays behind them, pickle can be much faster (dicts, str objects, lists)

In [103]:
import pickle
from joblib import dump, load

In [104]:
with open('dt.pkl', 'wb') as f:
    pickle.dump(dt, f)

In [106]:
dump(dt,'dt.joblib') 

['dt.joblib']

In [107]:
dt

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [108]:
del dt

In [109]:
dt

NameError: name 'dt' is not defined

In [110]:
dt = load('dt.joblib')

In [111]:
dt

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [112]:
dt.predict([[1,2,3,4]])

array(['virginica'], dtype=object)

In [113]:
del dt

In [114]:
with open('dt.pkl', 'rb') as f:
    dt = pickle.load(f)

In [115]:
dt

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [116]:
dt.predict([[1,2,3,4]])

array(['virginica'], dtype=object)

In [117]:
del det

NameError: name 'det' is not defined

In [118]:
def score(vect):
    dt = load('dt.joblib')
    return dt.predict(vect)

In [119]:
dt

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [153]:
del dt

In [154]:
pred = score([[1,2,3,4]])

TypeError: 'numpy.float64' object is not callable

In [155]:
pred

NameError: name 'pred' is not defined

* persisting models is very important in practice
* the whole idea of training models is using them to make predictions later on
* or in the case of something like neural networks, load them and incrementally continue training
* we are training with toy datasets, but in industry models may take a very long time to train
* and have complicated data transformations and feature engineering prior to actual training
* be sure to think about how you will organize code going forward so it's reusable and easy to run again if neeeded, or train on new data easily

In [125]:
def train(x,y,path):
    dt = DecisionTreeClassifier().fit(x,y)
    dump(dt,path)
    
def score(vect,path):
    mod = load(path)
    return mod.predict(vect)

### what if we wanted to add in PCA

* we can save our transformations as well, reload them and reapply them
* remember whatever we do to our training data we must do to new data to score of predict

In [142]:
def decompose(x, path = "pca.joblib"):
    pca = PCA(n_components=2).fit(x)
    dump(pca, path) 
    return pca.transform(x)

def train(x,y,path = "model.joblib"):
    dt = DecisionTreeClassifier().fit(x,y)
    dump(dt,path)
    return dt
    
def score(vect, pca_path = "pca.joblib", mod_path = "model.joblib"):
    pca = load(pca_path)
    mod = load(mod_path)
    return mod.predict(pca.transform(vect))

In [143]:
pca_x = decompose(x)
model = train(pca_x, y)

In [144]:
pred = score([[1,2,3,4]])

In [145]:
pred

array(['versicolor'], dtype=object)

#### What if we have 100M datapoints to score
* we definatly could do them all at once by feeding in one large matrix
* but maybe that won't fit in memory
* we could make a generator that feeds in one row at a time and runs the score function
* maybe multiprocessing would be faster? depends on the problem
* if multiprocessing, remember the score function loads 2 models, that is a lot of IO.  You'd likly be better off packing the data and models into tuples to save IO

In [ ]:
#def score(item):
#    pca = item[1]
#    mod = item[2]
#    return mod.predict(pca.transform(item[0]))

#data = [
#    [1,2,3,4], mod_object_1, mod_object2],
#    [1,2,3,4], mod_object_1, mod_object2],
#    [1,2,3,4], mod_object_1, mod_object2]
#]

In [ ]:
data = [
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
]

In [146]:
# we could mape the score function above to the data
# pool.map(score, data)

* the best approach will depend on the problem, but there is a lot of options to efficiently score and predict new data?

* once a model is saved what can we do with it?
* embed in a dashboard
* deploy as an API that can be pinged to get results
* share it with co workers...if you're nice of course :)
* use it to batch score overnight (lots of data points, think song recommendations for every spotify user)
* flow could be something like
    * parse your data across multiple executors/servers with your score function and model objects
    * make predictions and send them to a database or storeage somewhere
    * backend engineers make some API that pings with data, loads your model, spits back predictions
* something abstract is happening like this with most seaech querys performed
* the strings get sent to an API
* the api takes the string and runs some model/grabs results and sends the results back to be displayed

#### KNN Classifier
* https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
* https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

In [159]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [160]:
knn = KNeighborsClassifier(n_neighbors=5).fit(x,y)

In [161]:
yhat = knn.predict(x)

In [163]:
knn.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [164]:
acc = accuracy_score(y,yhat)
prec = precision_score(y, yhat, labels = knn.classes_, average="weighted")
rec = recall_score(y, yhat, labels = knn.classes_, average="weighted")
print(acc)
print(prec)
print(rec)

0.9666666666666667
0.9667867146858743
0.9666666666666667


In [165]:
precs = []
recs = []
accs = []
for k in [1,2,3,4,5,6,7,8,9,10]:
    knn = KNeighborsClassifier(n_neighbors=k).fit(x,y)
    yhat = knn.predict(x)
    acc = accuracy_score(y,yhat)
    prec = precision_score(y, yhat, labels = knn.classes_, average="weighted")
    rec = recall_score(y, yhat, labels = knn.classes_, average="weighted")
    precs.append(prec)
    recs.append(rec)
    accs.append(acc)
    print("K:{}".format(k))
    print("Accuracy:{}".format(acc))
    print("Precision:{}".format(prec))
    print("Recall:{}".format(rec))
    print("\n")

K:1
Accuracy:1.0
Precision:1.0
Recall:1.0


K:2
Accuracy:0.98
Precision:0.9811320754716981
Recall:0.98


K:3
Accuracy:0.96
Precision:0.96
Recall:0.96


K:4
Accuracy:0.96
Precision:0.96
Recall:0.96


K:5
Accuracy:0.9666666666666667
Precision:0.9667867146858743
Recall:0.9666666666666667


K:6
Accuracy:0.9733333333333334
Precision:0.9733333333333334
Recall:0.9733333333333334


K:7
Accuracy:0.9733333333333334
Precision:0.9738247863247864
Recall:0.9733333333333334


K:8
Accuracy:0.98
Precision:0.980125383486728
Recall:0.98


K:9
Accuracy:0.98
Precision:0.980125383486728
Recall:0.98


K:10
Accuracy:0.98
Precision:0.980125383486728
Recall:0.98




### SVM Classifier
* https://scikit-learn.org/stable/modules/svm.html/

In [166]:
from sklearn.svm import SVC

In [167]:
kernels = ["linear", "poly", "rbf", "sigmoid"]

In [168]:
for k in kernels:
    svm = SVC(kernel = k).fit(x,y)
    yhat = svm.predict(x)
    acc = accuracy_score(y,yhat)
    prec = precision_score(y, yhat, labels = knn.classes_, average="weighted")
    rec = recall_score(y, yhat, labels = knn.classes_, average="weighted")
    precs.append(prec)
    recs.append(rec)
    accs.append(acc)
    print("Kernel:{}".format(k))
    print("Accuracy:{}".format(acc))
    print("Precision:{}".format(prec))
    print("Recall:{}".format(rec))
    print("\n")

Kernel:linear
Accuracy:0.9933333333333333
Precision:0.9934640522875816
Recall:0.9933333333333333


Kernel:poly
Accuracy:0.98
Precision:0.980125383486728
Recall:0.98


Kernel:rbf
Accuracy:0.9866666666666667
Precision:0.9871794871794873
Recall:0.9866666666666667


Kernel:sigmoid
Accuracy:0.04
Precision:0.023604465709728868
Recall:0.04




C:\Users\raves\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\raves\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\raves\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\raves\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:14

##  Prediction

In [169]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

In [170]:
x1 = x.drop("sepal length (cm)", 1)
y1 = x["sepal length (cm)"]

In [171]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
knn = KNeighborsRegressor()
svr = SVR()

models = [lr, dt, knn, svr]

In [173]:
for mod in models:
    mod.fit(x1,y1)
    yhat = mod.predict(x1)
    mse = mean_squared_error(y1,yhat)
    print("Model:{}".format(mod))
    print("MSE:{}".format(mse))
    print("\n")

Model:LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)
MSE:0.09630269942460723


Model:DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')
MSE:0.0009333333333333338


Model:KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')
MSE:0.08234400000000003


Model:SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)
MSE:0.0893454354409234




C:\Users\raves\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


# What is some stuff we could start doing to make this model better

### Train and Test Split

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [23]:
clf.predict(x_test)

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

### Simple Validation

In [24]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

In [25]:
yhat_test = clf.predict(x_test)

In [26]:
accuracy_score(yhat_test, y_test)

1.0

In [30]:
precision_score(yhat_test, y_test, average = "weighted")

1.0

In [31]:
recall_score(yhat_test, y_test, average = "weighted")

1.0

In [34]:
con_matr = confusion_matrix(yhat_test, y_test)
con_matr

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [36]:
pd.DataFrame(con_matr, index = clf.classes_, columns = clf.classes_)

setosa  versicolor  virginica
setosa          10           0          0
versicolor       0           9          0
virginica        0           0         11

In [37]:
print(classification_report(yhat_test, y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



### Simple Collaborative Filtering
* java library for rec systems, super comprehensive
* https://www.librec.net/

#### User Based

In [174]:
# user item rating will be common
data = [
    ["A", "Avengers", 5],
    ["A", "Star Wars", 5],
    ["A", "Mean Girls", 1],
    ["A", "Mean Girls 2", 1],
    ["B", "Avengers", 2],
    ["B", "Star Wars", 5],
    ["B", "Mean Girls", 1],
    ["B", "Mean Girls 2", 1],
    ["C", "Avengers", 5],
    ["C", "Star Wars", 3],
    ["C", "Mean Girls", 1],
    ["C", "Mean Girls 2", 1]
]

In [175]:
# get a ratings matrix
ui_df = pd.DataFrame(data, columns = ["user", "movie", "rating"])

In [176]:
ratings_matrix = ui_df.pivot(index = "user", columns = "movie", values = "rating")

In [177]:
# rows are users columns are items (movies)
# could just as easily be products from Amazon
# or any website
# cells don't have to be ratings, could be purchase frequency
ratings_matrix

movie  Avengers  Mean Girls  Mean Girls 2  Star Wars
user                                                
A             5           1             1          5
B             2           1             1          5
C             5           1             1          3

In [178]:
from scipy.spatial.distance import cdist

In [179]:
cdist(ratings_matrix, ratings_matrix)

array([[0.        , 3.        , 2.        ],
       [3.        , 0.        , 3.60555128],
       [2.        , 3.60555128, 0.        ]])

In [180]:
user_user_sim = pd.DataFrame(cdist(ratings_matrix, ratings_matrix), index = ratings_matrix.index, 
                            columns = ratings_matrix.index)

In [182]:
user_user_sim

user    A         B         C
user                         
A     0.0  3.000000  2.000000
B     3.0  0.000000  3.605551
C     2.0  3.605551  0.000000

### what are we building essentially?

In [183]:
np.argsort(user_user_sim)

user  A  B  C
user         
A     0  2  1
B     1  0  2
C     2  0  1

In [184]:
np.argsort(user_user_sim).applymap(lambda x: user_user_sim.columns[x])

user  A  B  C
user         
A     A  C  B
B     B  A  C
C     C  A  B

In [74]:
# drop last row because we can't be most similar to ourselves
np.argsort(user_user_sim).applymap(lambda x: user_user_sim.columns[x]).iloc[:,1:2]

user  B
user   
A     C
B     A
C     A

In [185]:
# drop last row because we can't be most similar to ourselves
nearest_neighbor_df = np.argsort(user_user_sim).applymap(lambda x: user_user_sim.columns[x]).iloc[:,1:2]

* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html

In [186]:
nearest_neighbor_df.columns = ["nearest_neighbor"]

In [187]:
nearest_neighbor_df.to_dict("index")

{'A': {'nearest_neighbor': 'C'},
 'B': {'nearest_neighbor': 'A'},
 'C': {'nearest_neighbor': 'A'}}

In [83]:
ratings_matrix.to_dict("index")

{'A': {'Avengers': 5, 'Mean Girls': 1, 'Mean Girls 2': 1, 'Star Wars': 5},
 'B': {'Avengers': 2, 'Mean Girls': 1, 'Mean Girls 2': 1, 'Star Wars': 5},
 'C': {'Avengers': 5, 'Mean Girls': 1, 'Mean Girls 2': 1, 'Star Wars': 3}}

In [188]:
# once we have this data, we could go through and ad some sort of script that says
# recommend movies nearest neighbors like, but user hasn't seen

#### this was a high level example of a user-user collaborative filtering

In [189]:
user_user_sim

user    A         B         C
user                         
A     0.0  3.000000  2.000000
B     3.0  0.000000  3.605551
C     2.0  3.605551  0.000000

#### What if we did item-item

In [190]:
cdist(ratings_matrix.T, ratings_matrix.T)

array([[0.        , 5.74456265, 5.74456265, 3.60555128],
       [5.74456265, 0.        , 0.        , 6.        ],
       [5.74456265, 0.        , 0.        , 6.        ],
       [3.60555128, 6.        , 6.        , 0.        ]])

In [191]:
item_item_sim = pd.DataFrame(cdist(ratings_matrix.T, ratings_matrix.T), index = ratings_matrix.T.index, 
                            columns = ratings_matrix.T.index)

In [192]:
item_item_sim

movie         Avengers  Mean Girls  Mean Girls 2  Star Wars
movie                                                      
Avengers      0.000000    5.744563      5.744563   3.605551
Mean Girls    5.744563    0.000000      0.000000   6.000000
Mean Girls 2  5.744563    0.000000      0.000000   6.000000
Star Wars     3.605551    6.000000      6.000000   0.000000

* would be quite similar, if user saw Avengers and rated it high, we could recommend movies similar to the avengers
* this example has it backwards, but in reality we would have more users then items (how many users does Netflix have vs. movies?)  thus a user-user matrix is pretty huge.
* remember, simple rec systems are just some linear algebra, the concepts are pretty simple
    * get some sort of vector representation for your observations
    * find a way to quantify the similarity