## Numpy Arrays
* multi dimensional arrays or data
* can be 1d, 2d, 3d
* very computationally efficient to perform linear algebra operations over
* elementwise operations
* row and column wise calculations
* https://docs.scipy.org/doc/numpy-1.11.0/numpy-user-1.11.0.pdf

## Arrays vs. Matrix Class
* "Short Answer: Use Arrays."
* They are the standard vector/matrix/tensor type of numpy. Many numpy functions return arrays, not matrices.
* The array class is intended to be a general-purposen-dimensional array for many kinds of numerical computing, whilematrixis intended to facilitate linear algebracomputations specifically.

In [5]:
import numpy as np

#### 1-D arrays
* note his only has one demension
* we could use a method called reshape to change this (we will get into this more later on)

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a.shape

(5,)

In [4]:
b = np.reshape(a, (5,1))
b.shape

(5, 1)

In [9]:
b[1,0]

2

In [10]:
a[1]

2

#### indexing and slicing

In [11]:
a[0]

1

In [12]:
a[0:2]

array([1, 2])

In [13]:
a[1:3]

array([2, 3])

In [14]:
a[-1]

5

In [15]:
type(a)

numpy.ndarray

In [16]:
for i in a:
    print(i)

1
2
3
4
5


#### looping
* numpy loops through the left most axis

In [17]:
array = np.array([
    [1,2,3],
    [2,3,4]
])

array.shape

(2, 3)

In [18]:
# since we have 2 items in the first axis we will end up with 2 items in our iteration
for i in array:
    print(i)

[1 2 3]
[2 3 4]


In [22]:
array = np.array([
    [1,2,3,4],
    [2,3,4,4],
    [2,3,4,4]
])

array1 = np.array([
    [5,6,7,4],
    [4,6,9,4],
    [2,3,4,4]
])

In [23]:
# depth 2
# rows 3
# columns 4
tensor = np.array([array, array1])
tensor.shape

(2, 3, 4)

* remember numpy will iterate left most index
* in this 3-d cube, it's iterating the dpeth
* so we end up printing our 2 initial matrices

In [24]:
for i in tensor:
    print(i)

[[1 2 3 4]
 [2 3 4 4]
 [2 3 4 4]]
[[5 6 7 4]
 [4 6 9 4]
 [2 3 4 4]]


#### performing matrix operations
* axis 0 is the y axis
* the up and down axis
* the number of rows
* so any operation done on axis 0 is going to be columns
* done up and down
* axis 1 is the length of our array
* any summing or anything is done across our dataframe
* doing some operation to our rows

In [25]:
array = np.array([
    [1,2,3,4],
    [2,3,4,4],
    [2,3,4,4]
])

In [26]:
array.shape

(3, 4)

In [27]:
array

array([[1, 2, 3, 4],
       [2, 3, 4, 4],
       [2, 3, 4, 4]])

In [28]:
np.sum(array, axis = 0)

array([ 5,  8, 11, 12])

In [34]:
np.sum(array, axis = 1)

array([10, 13, 13])

In [37]:
array.dtype

dtype('int32')

In [38]:
np.median(array, axis = 0)

array([2., 3., 4., 4.])

* the other option would be to loop which is far more costly of an operation

In [39]:
for i in array:
    print(sum(i))

10
13
13


In [40]:
for i in array.T:
    print(sum(i))

5
8
11
12


In [39]:
array

array([[1, 2, 3, 4],
       [2, 3, 4, 4],
       [2, 3, 4, 4]])

#### tranpose, turn rows into columns

In [40]:
array.T

array([[1, 2, 2],
       [2, 3, 3],
       [3, 4, 4],
       [4, 4, 4]])

<h3 style="color:blue">Make a 2-d array in numpy:</h3>
<p style="color:blue">- find the row wise mean</p>
<p style="color:blue">- find the column wise mean</p>
<p style="color:blue">- do the same for the transpose of the array you've made</p>
<p style="color:blue">- check if matrix square</p>
<p style="color:blue">- multiple the matrix by transpose</p>

In [52]:
a = np.ones([3,4])


print(a.sum(0))
print(a.sum(1))

b = a.T

print(b.sum(0))
print(b.sum(1))


if(a.shape[0]!=a.shape[1]):
    print("Not a square!")


c = np.dot(a,b)

print(c.sum(0))
print(c.sum(1))


if(c.shape[0]!=c.shape[1]):
    print("Not a square!")
else:
    print("Square as me!")


[3. 3. 3. 3.]
[4. 4. 4.]
[4. 4. 4.]
[3. 3. 3. 3.]
Not a square!
[12. 12. 12.]
[12. 12. 12.]
Square as me!


#### other useful metrics
* https://docs.scipy.org/doc/numpy/reference/generated/numpy.quantile.html
* https://docs.scipy.org/doc/numpy/reference/generated/numpy.percentile.html

In [46]:
array

array([[1101, 2020, 3212],
       [2212, 3112, 4121]])

In [47]:
np.std(array, axis = 0)

array([555.5, 546. , 454.5])

In [48]:
np.mean(array, axis = 0)

array([1656.5, 2566. , 3666.5])

In [49]:
np.min(array, axis = 0)

array([1101, 2020, 3212])

In [50]:
np.max(array, axis = 0)

array([2212, 3112, 4121])

In [51]:
np.quantile(array,.5, axis = 0)

array([1656.5, 2566. , 3666.5])

In [52]:
np.percentile(array,.5, axis = 0)

array([1106.555, 2025.46 , 3216.545])

#### reshape
* change the shape of your data
* adding indices
* https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

In [53]:
# this is indexed by one element
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [54]:
array.shape

(4,)

In [55]:
array[0]

1

In [56]:
array = np.reshape(array, (4,1))
array.shape

(4, 1)

In [57]:
array[0][0]

1

In [58]:
# we've now added two dimension using reshape
array1 = np.reshape(array,(2,2))

In [59]:
array1

array([[1, 2],
       [3, 4]])

In [60]:
array = np.array([1,2,3,4,5,6,7,8])

In [61]:
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
array1 = np.reshape(array, (2,2,2))

In [63]:
array1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [68]:
array1.shape

(2, 2, 2)

In [69]:
for i in array1:
    print(i, "\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 



#### norm of a vector
* https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html
* defaults to the l2 norm

In [66]:
array = np.array([1,2,3])
np.linalg.norm(array)

3.7416573867739413

In [67]:
np.sqrt(14)

3.7416573867739413

#### matrix multiplication/dot product

In [53]:
array = np.array([
    [1,2],
    [2,3]
])

array1 = np.array([
    [5,6],
    [4,6]
])

In [54]:
# shortcut
array@array1

array([[13, 18],
       [22, 30]])

In [143]:
np.matmul(array, array1)

array([[13, 18],
       [22, 30]])

In [144]:
np.dot(array, array1)

array([[13, 18],
       [22, 30]])

#### remember the dimension constraints

In [55]:
array = np.array([
    [1,2,3],
    [2,3,3]
])

array1 = np.array([
    [5,6,2],
    [4,6,1]
])

In [56]:
print(array.shape, array1.shape)

(2, 3) (2, 3)


In [57]:
assert array.shape[1] == array1.shape[0], "The dimensions aren't aligned"

array@array1

AssertionError: The dimensions aren't aligned

In [103]:
array = np.array([
    [1,2,3],
    [2,3,3]
])

array1 = np.array([
    [5,6,2,5,3,2],
    [4,6,1,3,4,5],
    [2,3,2,2,1,3]
])

print(array.shape, array1.shape)
assert array.shape[1] == array1.shape[0], "The dimensions aren't aligned"

array@array1

(2, 3) (3, 6)


array([[19, 27, 10, 17, 14, 21],
       [28, 39, 13, 25, 21, 28]])

<h3 style="color:blue">Make udf that:</h3>
<p style="color:blue">- takes 2 2-d arrays as params</p>
<p style="color:blue">- tests to make sure they can be multipled using assert</p>
<p style="color:blue">- return the dot product of the two matrices</p>

In [60]:
def rafdot(m1, m2):
    assert m1.shape[1] == m2.shape[0], "The dimensions aren't aligned"
    return m1@m2

array = np.array([
    [1,2,3],
    [2,3,3]
])

array1 = np.array([
    [5,6,2,5,3,2],
    [4,6,1,3,4,5],
    [2,3,2,2,1,3]
])

array2 = np.array([
    [5,6,2,5,3,2],
    [4,6,1,3,4,5]])

c = rafdot(array,array1)
print(c)

c = rafdot(array,array2)
print(c)

[[19 27 10 17 14 21]
 [28 39 13 25 21 28]]


AssertionError: The dimensions aren't aligned

#### broadcasting
* expand the dimension to add to a matrix
* https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [68]:
array = np.array([
    [1,2,3],
    [2,3,3]
])

array1 = np.array([1,1])
array1 = np.reshape(array1, (2,1))

In [70]:
array

array([[1, 2, 3],
       [2, 3, 3]])

In [71]:
array1

array([[1],
       [1]])

In [72]:
np.add(array, array1)

array([[2, 3, 4],
       [3, 4, 4]])

In [120]:
np.subtract(array, array1)

array([[0, 1, 2],
       [1, 2, 2]])

In [73]:
array + array1

array([[2, 3, 4],
       [3, 4, 4]])

In [74]:
array - array1

array([[0, 1, 2],
       [1, 2, 2]])

#### elementwise squaring
* this is the elementwise operations arrays that make arrays so powerful

In [127]:
array**5

array([[  1,  32, 243],
       [ 32, 243, 243]])

In [128]:
np.power(array, 5)

array([[  1,  32, 243],
       [ 32, 243, 243]])

<h3 style="color:blue">Make udf that:</h3>
<p style="color:blue">- takes 2 2-d arrays as params</p>
<p style="color:blue">- iterates the rows and columns and squares each element</p>
<p style="color:blue">- puts the squared items in a list</p>
<p style="color:blue">- returns the list</p>

In [64]:
def raf_square(m1,m2):
    flist = []
    for k in m1, m2:
        c = k*k
        flist.append(c)
    return flist

raf_square(array,array1)

[array([[1, 4, 9],
        [4, 9, 9]]), array([[25, 36,  4, 25,  9,  4],
        [16, 36,  1,  9, 16, 25],
        [ 4,  9,  4,  4,  1,  9]])]

#### argmax and min
* returns the index of the max/min value
* In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned.
* https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html

In [3]:
array = np.array([1,2,3,4,5])
np.argmax(array)

4

In [4]:
np.argmin(array)

0

In [8]:
array = np.array([
    [1,6,3],
    [3,10,5],
    [15,8,9]
])

In [9]:
np.argmax(array, axis = 0) # column level

array([2, 1, 2])

In [10]:
np.argmax(array, axis = 1) # row level

array([1, 1, 0])

#### let's say these are distances
* each row is an item
* and each column is the distance to a cluster
array = np.array([

In [71]:
array = np.array([
    [1,6,3],
    [3,10,5],
    [15,8,9]
])

In [72]:
# this could then give us the index of the min distance
np.argmin(array, axis = 1)

array([0, 0, 1], dtype=int64)

In [73]:
items = ["item_A", "item_B", "item_C"]
clusters = ["A", "B", "C"]
closest_cluster = np.argmin(array, axis = 1)

In [74]:
closest_cluster_labels = [clusters[idx] for idx in closest_cluster]
closest_cluster_labels

['A', 'A', 'B']

In [69]:
list(zip(items, closest_cluster_labels))

[('item_A', 'A'), ('item_B', 'A'), ('item_C', 'B')]

In [70]:
array = np.array([
    items,
    closest_cluster_labels
]).T

array

array([['item_A', 'A'],
       ['item_B', 'A'],
       ['item_C', 'B']], dtype='<U6')

In [81]:
array = np.array([
    items,
    [clusters[idx] for idx in np.argmin(array, axis = 1)]
]).T

array

array([['item_A', 'B'],
       ['item_B', 'B'],
       ['item_C', 'B']], dtype='<U6')

In [82]:
np.argmax(np.array([1,1,2,2,5,5,5]))

4

#### argsort

In [75]:
array = np.array([1,3,6,0,51,12])

In [76]:
sorted_args = np.argsort(array)

In [77]:
[array[idx] for idx in sorted_args]

[0, 1, 3, 6, 12, 51]

In [78]:
array = np.array([
    [1,6,3],
    [3,10,5],
    [15,8,9]
])

In [79]:
items = ["item_A", "item_B", "item_C"]
clusters = ["A", "B", "C"]
closest_cluster = np.argmin(array, axis = 1)

In [81]:
array

array([[ 1,  6,  3],
       [ 3, 10,  5],
       [15,  8,  9]])

In [82]:
np.argsort(array, axis = 1)

array([[0, 2, 1],
       [0, 2, 1],
       [1, 2, 0]], dtype=int64)

In [83]:
def myfunc(x):
    items = ["item_A", "item_B", "item_C"]
    return items[x]

vectorized_func = np.vectorize(myfunc)

In [84]:
vectorized_func(array)

IndexError: list index out of range

## Distance Measures
* used in many ML algorithms
* rec systems, kmeans, knn, decision trees
* https://docs.scipy.org/doc/scipy/reference/spatial.distance.html

#### euclidean distance
* magnitude makes a difference

In [2]:
a = np.array([1,2,3])
b = np.array([4,2,1])

In [15]:
np.sqrt(sum((a-b)**2))

3.605551275463989

#### cosine similarity

In [18]:
np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))

0.6415330278717848

#### jaccard coefficient

In [32]:
a = ["the", "old", "man", "by", "the", "sea"]
b = ["the", "old", "man", "by", "the", "chair"]

In [39]:
def jaccard_similarity(a, b):
    return len(set(a).intersection(set(b))) / len(set(a).union(set(b)))

In [40]:
jaccard_similarity(a,b)

0.6666666666666666

#### distance matrix
* pdist returns a reduced distance matrix, since they are symetrical
* squareform makes this a dense form

In [85]:
from scipy.spatial.distance import pdist, squareform

In [86]:
array = np.array([
    [1,2,3,4],
    [2,4,2,1],
    [2,3,4,5]
    
])

In [87]:
squareform(pdist(array, "euclidean"))

array([[0.        , 3.87298335, 2.        ],
       [3.87298335, 0.        , 4.58257569],
       [2.        , 4.58257569, 0.        ]])

In [103]:

xdata = np.array([0.0,1.0])
ydata = np.array([0.1,0.9])

data_pred = xdata.T * xdata.T

A = np.vstack([xdata,np.ones(len(xdata))]).T


print(ydata)
print(xdata)
print(A)


print (np.linalg.lstsq(A, ydata))

# the model has the following face y = a + bx
b, a = np.linalg.lstsq(A, ydata)[0]
print("y = "+str(a)+'x + '+str(b))

[0.1 0.9]
[0. 1.]
[[0. 1.]
 [1. 1.]]
(array([0.8, 0.1]), array([], dtype=float64), 2, array([1.61803399, 0.61803399]))
y = 0.09999999999999992x + 0.8


C:\Users\raves\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  
C:\Users\raves\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


In [109]:
#find if a number is prime
#find if it is a prime of goldbach and the primes that build it


def isprime(number):
    if(number%2):
        if(number!=2):
            return 0
        else:
            return 1
    dividers = np.arange(number,1,2)
    print(dividers)
    for k in dividers:
        if number%divider:
            return 0
    return 1 



0


### Pandas
* data wrangling
* groupby
* extension of numpys to add a dataframe capability
* similar to R dataframes
* integrates with numpy
* https://pandas.pydata.org/

In [123]:
import pandas as pd

## Series
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html
* One-dimensional ndarray with axis labels (including time series)

In [125]:
vals = [1,2,3,4,5]
idxs = ["a","b","c","d","e"]

my_series = pd.Series(vals, idxs)

In [126]:
my_series[["a", "b"]]

a    1
b    2
dtype: int64

### Dataframe
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html
* core object in pandas
* 2 dimensional
* index and columns

In [127]:
array1 = np.array([
    [5,6,2,5,3,2],
    [4,6,1,3,4,5],
    [2,3,2,2,1,3]
])

In [128]:
df = pd.DataFrame(array1)

In [130]:
dir(df)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 

In [132]:
df.head(2)

0  1  2  3  4  5
0  5  6  2  5  3  2
1  4  6  1  3  4  5

In [135]:
df

0  1  2  3  4  5
0  5  6  2  5  3  2
1  4  6  1  3  4  5
2  2  3  2  2  1  3

In [136]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [137]:
df.columns

RangeIndex(start=0, stop=6, step=1)

#### change headers

In [140]:
df.columns = ["R", "b", "c", "d", "e", "f"]

In [141]:
df

R  b  c  d  e  f
0  5  6  2  5  3  2
1  4  6  1  3  4  5
2  2  3  2  2  1  3

In [142]:
df.dtypes

R    int32
b    int32
c    int32
d    int32
e    int32
f    int32
dtype: object

#### accessing columns
* returns series
* index still attached to the series

In [145]:
df["R"]

0    5
1    4
2    2
Name: R, dtype: int32

In [147]:
type(df["R"])

pandas.core.series.Series

In [155]:
df["R"].tolist()

[5, 4, 2]

In [151]:
df["R"].index

RangeIndex(start=0, stop=3, step=1)

In [157]:
df[["c", "b"]]

c  b
0  2  6
1  1  6
2  2  3

#### index subsetting
* iloc[] is position selecting
* iloc[rows, columns]
* rows/columns can be a list of indicies (integers) or use : to seperate a range
* [2:] means give me 2 and everything after for slicing
* [1] means give me index 1
* [1,2,3] means give me index 1,2,3
* [1],[0,1] means give me row 1 and columns 0 and 1

In [164]:
df.iloc[0]

R    5
b    6
c    2
d    5
e    3
f    2
Name: 0, dtype: int32

In [165]:
# need integer based subsetting
df.iloc[1,[0,1,2]]

R    4
b    6
c    1
Name: 1, dtype: int32

In [166]:
df.iloc[[1,2]]

R  b  c  d  e  f
1  4  6  1  3  4  5
2  2  3  2  2  1  3

In [167]:
df.iloc[[0,2,1]]

R  b  c  d  e  f
0  5  6  2  5  3  2
2  2  3  2  2  1  3
1  4  6  1  3  4  5

In [168]:
df.iloc[0:,0:]

R  b  c  d  e  f
0  5  6  2  5  3  2
1  4  6  1  3  4  5
2  2  3  2  2  1  3

In [169]:
df.iloc[0:,0:1]

R
0  5
1  4
2  2

In [170]:
df.iloc[[1],[0,1]]

R  b
1  4  6

#### loc
* used if we have labels and not integer indec

In [171]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [172]:
df.index = ["aa", "bb", "cc"]

In [173]:
df

R  b  c  d  e  f
aa  5  6  2  5  3  2
bb  4  6  1  3  4  5
cc  2  3  2  2  1  3

In [174]:
df.loc["aa"]

R    5
b    6
c    2
d    5
e    3
f    2
Name: aa, dtype: int32

In [175]:
df.loc[["aa", "bb"]]

R  b  c  d  e  f
aa  5  6  2  5  3  2
bb  4  6  1  3  4  5

In [179]:
df.loc[["aa"], ["R","b"]]

R  b
aa  5  6

<h3 style="color:blue">how might we</h3>
<p style="color:blue">- filter if we have a large number of indices?</p>
<p style="color:blue">- we don't want to type out a list of 1000s of index labels</p>

In [181]:
rows = ["aa", "bb"]
cols = ["R", "c"]

df.loc[rows,cols]

R  c
aa  5  2
bb  4  1

#### subset for columns

In [184]:
df1 = df[[ "b", "c", "d"]]

In [185]:
df1

b  c  d
aa  6  2  5
bb  6  1  3
cc  3  2  2

#### describe

In [188]:
df1.describe()

b         c         d
count  3.000000  3.000000  3.000000
mean   5.000000  1.666667  3.333333
std    1.732051  0.577350  1.527525
min    3.000000  1.000000  2.000000
25%    4.500000  1.500000  2.500000
50%    6.000000  2.000000  3.000000
75%    6.000000  2.000000  4.000000
max    6.000000  2.000000  5.000000

#### correlate

In [187]:
df1.corr()

b         c         d
b  1.000000 -0.500000  0.755929
c -0.500000  1.000000  0.188982
d  0.755929  0.188982  1.000000

#### summations

In [189]:
df1.sum(axis = 0)

b    15
c     5
d    10
dtype: int64

In [194]:
a = df1.sum(axis = 1)
print(type(a))

<class 'pandas.core.series.Series'>


#### median

In [191]:
df1.median(axis = 0)

b    6.0
c    2.0
d    3.0
dtype: float64

#### new column

In [195]:
df1["class"] = ["AA", "AA", "BB"]

C:\Users\raves\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [198]:
df1

b  c  d class
aa  6  2  5    AA
bb  6  1  3    AA
cc  3  2  2    BB

In [199]:
df1.groupby("class").sum()

b  c  d
class          
AA     12  3  8
BB      3  2  2

In [200]:
df1.groupby("class").count()

b  c  d
class         
AA     2  2  2
BB     1  1  1

In [201]:
# count distinct
df1.groupby("class").nunique()

b  c  d  class
class                
AA     1  2  2      1
BB     1  1  1      1

#### reset index

In [47]:
df1.groupby("class").count().index

Index(['AA', 'BB'], dtype='object', name='class')

In [48]:
df1.groupby("class").count().reset_index()

class  a  b  c  d
0    AA  2  2  2  2
1    BB  1  1  1  1

In [203]:
df1.groupby("class").count().reset_index().index

RangeIndex(start=0, stop=2, step=1)

#### reading in csv

In [210]:
path = "../data/iris.csv"
df = pd.read_csv(path, sep = ",")

In [211]:
df.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

<h3 style="color:blue">read in the iris csv:</h3>
<p style="color:blue">- find the descriptive statistics</p>
<p style="color:blue">- create a correlation matrix </p>

#### subset on rules

In [217]:
df1 = df[df["sepal.length"] > 5]
df1.shape

(118, 5)

In [218]:
df1 = df[(df["sepal.length"] > 6) & (df["sepal.width"] > 3)]
df1.shape

(23, 5)

In [219]:
df1 = df[df["variety"] == "Setosa"]
df1.shape

(50, 5)

#### isin()

In [225]:
df["variety"].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [226]:
lst = ["Setosa", "Versicolor"]

df1 = df[df["variety"].isin(lst)]
df1.shape

(100, 5)

#### like

In [227]:
df1 = df[df["variety"].str.contains("Versi")]
df1.shape

(50, 5)

#### apply

In [228]:
def my_func(x):
    return -x

In [229]:
df.head(1)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa

In [230]:
df["sepal.length"] = df["sepal.length"].apply(my_func)

In [231]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0          -5.1          3.5           1.4          0.2  Setosa
1          -4.9          3.0           1.4          0.2  Setosa
2          -4.7          3.2           1.3          0.2  Setosa
3          -4.6          3.1           1.5          0.2  Setosa
4          -5.0          3.6           1.4          0.2  Setosa

In [232]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [233]:
cols = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width']

In [234]:
for col in cols:
    df[col] = df[col].apply(my_func)

In [236]:
df.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1         -3.5          -1.4         -0.2  Setosa
1           4.9         -3.0          -1.4         -0.2  Setosa
2           4.7         -3.2          -1.3         -0.2  Setosa
3           4.6         -3.1          -1.5         -0.2  Setosa
4           5.0         -3.6          -1.4         -0.2  Setosa

In [237]:
df["sepal.length"] = df["sepal.length"].apply(lambda x: -x)

In [238]:
df.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0          -5.1         -3.5          -1.4         -0.2  Setosa
1          -4.9         -3.0          -1.4         -0.2  Setosa
2          -4.7         -3.2          -1.3         -0.2  Setosa
3          -4.6         -3.1          -1.5         -0.2  Setosa
4          -5.0         -3.6          -1.4         -0.2  Setosa

#### datatypes

In [239]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [240]:
df["sepal.length"] = df["sepal.length"].apply(str)

In [241]:
df.dtypes

sepal.length     object
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

#### get dummies
* for string or object variables
* can specify specific columns
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html

<h3 style="color:blue">what might we need dummies for?</h3>

In [242]:
df = pd.get_dummies(df)

In [243]:
df.head()

sepal.width  petal.length  petal.width  sepal.length_-4.3  \
0         -3.5          -1.4         -0.2                  0   
1         -3.0          -1.4         -0.2                  0   
2         -3.2          -1.3         -0.2                  0   
3         -3.1          -1.5         -0.2                  0   
4         -3.6          -1.4         -0.2                  0   

   sepal.length_-4.4  sepal.length_-4.5  sepal.length_-4.6  sepal.length_-4.7  \
0                  0                  0                  0                  0   
1                  0                  0                  0                  0   
2                  0                  0                  0                  1   
3                  0                  0                  1                  0   
4                  0                  0                  0                  0   

   sepal.length_-4.8  sepal.length_-4.9  ...  sepal.length_-7.1  \
0                  0                  0  ...                  0   
1                  0                  1  ...                  0   
2                  0                  0  ...                  0   
3                  0                  0  ...                  0   
4                  0                  0  ...                  0   

   sepal.length_-7.2  sepal.length_-7.3  sepal.length_-7.4  sepal.length_-7.6  \
0                  0                  0                  0                  0   
1                  0                  0                  0                  0   
2                  0                  0                  0                  0   
3                  0                  0                  0                  0   
4                  0                  0                  0                  0   

   sepal.length_-7.7  sepal.length_-7.9  variety_Setosa  variety_Versicolor  \
0                  0                  0               1                   0   
1                  0                  0               1                   0   
2                  0                  0               1                   0   
3                  0                  0               1                   0   
4                  0                  0               1                   0   

   variety_Virginica  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 41 columns]

In [244]:
col_1 = np.array(["A", "B", "C"])
col_2 = np.array(["AA", "BB", "CC"])

df = pd.DataFrame({
    "col_1":col_1,
    "col_2":col_2
})

df

col_1 col_2
0     A    AA
1     B    BB
2     C    CC

<h3 style="color:blue">perform get dummies on col_1 only?</h3>

#### iterate

In [246]:
for idx, r in df.head(5).iterrows():
    print(idx, r)

0 col_1     A
col_2    AA
Name: 0, dtype: object
1 col_1     B
col_2    BB
Name: 1, dtype: object
2 col_1     C
col_2    CC
Name: 2, dtype: object


In [249]:
for idx, r in df.head(5).iterrows():
    print(r)

col_1     A
col_2    AA
Name: 0, dtype: object
col_1     B
col_2    BB
Name: 1, dtype: object
col_1     C
col_2    CC
Name: 2, dtype: object


#### tolist()

In [252]:
df["col_1"].tolist()

['A', 'B', 'C']

<h3 style="color:blue">Using iris, group by variety and find the count of the other columns?</h3>
<h3 style="color:blue">Using iris, group by variety and find the sum of the other columns?</h3>

In [253]:
col_1 = np.array(["A", "B", "C", "D", "E"])
col_2 = np.array(["A", "B", "C"])

df = pd.DataFrame({
    "col_1":col_1,
    "col_1_ind":1
})

df1 = pd.DataFrame({
    "col_1":col_2,
    "col_2_ind":1
})
df

col_1  col_1_ind
0     A          1
1     B          1
2     C          1
3     D          1
4     E          1

In [254]:
df1

col_1  col_2_ind
0     A          1
1     B          1
2     C          1

#### concat
* https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [255]:
pd.concat([df, df1], axis = 0)

C:\Users\raves\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


col_1  col_1_ind  col_2_ind
0     A        1.0        NaN
1     B        1.0        NaN
2     C        1.0        NaN
3     D        1.0        NaN
4     E        1.0        NaN
0     A        NaN        1.0
1     B        NaN        1.0
2     C        NaN        1.0

#### merge
* https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.merge.html
* assumes inner join

In [257]:
df.merge(df1, how = "inner", left_on = "col_1", right_on = "col_1")

col_1  col_1_ind  col_2_ind
0     A          1          1
1     B          1          1
2     C          1          1

In [258]:
df.merge(df1, how = "left", left_on = "col_1", right_on = "col_1")

col_1  col_1_ind  col_2_ind
0     A          1        1.0
1     B          1        1.0
2     C          1        1.0
3     D          1        NaN
4     E          1        NaN

## Data Imputation
* https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html#pandas.DataFrame.interpolate
* missing values
* When summing data, NA (missing) values will be treated as zero.
* If the data are all NA, the result will be 0.
* Cumulative methods like cumsum() and cumprod() ignore NA values by default, but preserve them in the resulting arrays. To override this behaviour and include NA values, use skipna=False.


In [259]:
import pandas as pd
data = [1,2,3,4,None,5,2,1]
df = pd.DataFrame(data)

In [260]:
df

0
0  1.0
1  2.0
2  3.0
3  4.0
4  NaN
5  5.0
6  2.0
7  1.0

In [261]:
df.isna()

0
0  False
1  False
2  False
3  False
4   True
5  False
6  False
7  False

In [262]:
df.notna()

0
0   True
1   True
2   True
3   True
4  False
5   True
6   True
7   True

In [263]:
df.fillna(0)

0
0  1.0
1  2.0
2  3.0
3  4.0
4  0.0
5  5.0
6  2.0
7  1.0

In [264]:
df.fillna(100)

0
0    1.0
1    2.0
2    3.0
3    4.0
4  100.0
5    5.0
6    2.0
7    1.0

In [266]:
df.dropna(axis=0)

0
0  1.0
1  2.0
2  3.0
3  4.0
5  5.0
6  2.0
7  1.0

In [267]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7]

In [268]:
df.fillna(df.mean())

0
0  1.000000
1  2.000000
2  3.000000
3  4.000000
4  2.571429
5  5.000000
6  2.000000
7  1.000000

In [269]:
df.fillna(df.median())

0
0  1.0
1  2.0
2  3.0
3  4.0
4  2.0
5  5.0
6  2.0
7  1.0

In [270]:
df[0].fillna(df[0].mean()).reset_index()

index         0
0      0  1.000000
1      1  2.000000
2      2  3.000000
3      3  4.000000
4      4  2.571429
5      5  5.000000
6      6  2.000000
7      7  1.000000

## Json data

In [301]:
print(os.getcwd())

dir(os.getcwd())

import glob
path = glob.glob('../data/ca*')
print(path)

C:\Users\raves\Documents\GitHub\python_for_analytics\lectures
['../data\\ca.json']


In [100]:
with open(path, "r") as file:
    line = file.readlines()
    for l in line[0:50]:
        print(l)

In [297]:

columns = ["age", "job", "city"]
data = [
    [31, "data scientist", "chicago"],
    [28, "data scientist", "new york"],
    [28,None,None]
]

df = pd.DataFrame(data, columns = columns)
df

age             job      city
0   31  data scientist   chicago
1   28  data scientist  new york
2   28            None      None

df

In [303]:
df = pd.read_json('../data/ca.json')

ValueError: Expected object or value

In [304]:
df

age             job      city
0   31  data scientist   chicago
1   28  data scientist  new york
2   28            None      None

* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.json_normalize.html

* Nested JSON files can be time consuming and difficult process to flatten and load into Pandas.
* Let’s unpack the works column into a standalone dataframe. We’ll also grab the flat columns.
* nycphil = json_normalize(d['programs'])

In [305]:
data = [
        {'id': 1, 'name': "Cole Volk",'fitness': 
             {'height': 130, 'weight': 60}},
    
        {'name': "Mose Reg",'fitness': 
             {'height': 130, 'weight': 60}},
    
        {'id': 2, 'name': 'Faye Raker','fitness': 
             {'height': 130, 'weight': 60}}
]

In [306]:
from pandas.io.json import json_normalize

In [308]:
json_normalize(data)

id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mose Reg             130              60
2  2.0  Faye Raker             130              60

In [309]:
json_normalize(data, max_level = 0)

id        name                        fitness
0  1.0   Cole Volk  {'height': 130, 'weight': 60}
1  NaN    Mose Reg  {'height': 130, 'weight': 60}
2  2.0  Faye Raker  {'height': 130, 'weight': 60}

In [311]:
data = [
        {'state': 'Florida','shortname': 'FL',
            'info': {'governor': 'Rick Scott', "gender":"m"},
            'counties': [{'name': 'Dade', 'population': 12345},
                         {'name': 'Broward', 'population': 40000},
                         {'name': 'Palm Beach', 'population': 60000}]},
    
         {'state': 'Ohio', 'shortname': 'OH',
          'info': {'governor': 'John Kasich', "gender":"m"},
          'counties': [{'name': 'Summit', 'population': 1234},
                       {'name': 'Cuyahoga', 'population': 1337}]}
]

In [312]:
json_normalize(data, max_level = 0)

state shortname                                        info  \
0  Florida        FL   {'governor': 'Rick Scott', 'gender': 'm'}   
1     Ohio        OH  {'governor': 'John Kasich', 'gender': 'm'}   

                                            counties  
0  [{'name': 'Dade', 'population': 12345}, {'name...  
1  [{'name': 'Summit', 'population': 1234}, {'nam...

In [313]:
json_normalize(data, max_level = 1)

state shortname                                           counties  \
0  Florida        FL  [{'name': 'Dade', 'population': 12345}, {'name...   
1     Ohio        OH  [{'name': 'Summit', 'population': 1234}, {'nam...   

  info.governor info.gender  
0    Rick Scott           m  
1   John Kasich           m

In [33]:
json_normalize(data)

state shortname                                           counties  \
0  Florida        FL  [{'name': 'Dade', 'population': 12345}, {'name...   
1     Ohio        OH  [{'name': 'Summit', 'population': 1234}, {'nam...   

  info.governor info.gender  
0    Rick Scott           m  
1   John Kasich           m

In [314]:
# make each row a county, then start parsing data as such
json_normalize(data, "counties", [["info","governor"], ["info", "gender"]])

name  population info.governor info.gender
0        Dade       12345    Rick Scott           m
1     Broward       40000    Rick Scott           m
2  Palm Beach       60000    Rick Scott           m
3      Summit        1234   John Kasich           m
4    Cuyahoga        1337   John Kasich           m

## Chunks
* Can use chunks to process pieces of a dataframe at a time if it won't fit into memory

In [317]:
import pandas as pd

In [321]:
chunk_size = 20

In [322]:
path = "../data/iris.csv"

In [323]:
for c in pd.read_csv(path, chunksize = chunk_size):
    print(c.shape)

(20, 5)
(20, 5)
(20, 5)
(20, 5)
(20, 5)
(20, 5)
(20, 5)
(10, 5)


In [324]:
for c in pd.read_csv(path, chunksize = chunk_size):
    df = c.groupby("variety").sum()
    print(df.shape)

(1, 4)
(1, 4)
(2, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
